### ISSUE TITLE
Add description text to checkmark states

### ISSUE THREAD

**Issue by kblst** [Roam-Research/issues#1]
As a user, I need to understand if Roam has saved my data so that I can sleep at night knowing that I won't lose all of my thoughts and notes.

AC
- A grey checkmark has accompanying text "saved locally" or "not synced"
- An orange checkmark has accompanying text "updating" or "syncing in process"
- No checkmark "synced"

**Comment by filipesilva** [comment]
Heya, I'm adding these tooltips:

![image](https://user-images.githubusercontent.com/4172079/79879031-1407e580-83e6-11ea-9284-860d1004d573.png)

![image](https://user-images.githubusercontent.com/4172079/79879107-2f72f080-83e6-11ea-95bf-e850c878fda5.png)

![image](https://user-images.githubusercontent.com/4172079/79879194-487ba180-83e6-11ea-806f-fce2dacf50cd.png)

I didn't add a state/tooltip for when it's done though. Still on the fence if one is needed. Some tools, like Google Keep, have one and I find it nice. But if we can do without, it's one less thing for people to think about.

**Comment by ryanguill** [comment]
IMO a checkmark signifies that something is _done_ not in progress.  I agree we need a done state, and have been under the assumption that the checkmark was showing that things were synced, not still syncing.  Can you use something like vertical dots or a circle of different colors for the syncing and then a checkmark for done?

**Comment by filipesilva** [comment]
@ryanguill just to be clear, when nothing is shown that means it's done. Was this your understanding as well?

**Comment by sambbaron** [comment]
I agree. I think a checkmark that changes colors is confusing, also not accessible for color-blind, etc. I would prefer a word and an icon. For example, "syncing" with a spinner, and "synced" with a checkmark.

**Comment by smurfman111** [comment]
100% agree. Never understood the idea of the checkmark in the first place other than if everything is good to go. Also, I still get uneasy if I see "nothing"... i would actually prefer to see a checkmark or some little symbol there all the time when we are synched and good to go... and then have a red X or something when there is a problem synching to servers... or like a red offline icon like wifi symbol with a red line through it or something. And then when in middle of synching would like to see something like a Cloud symbol/icon. Or even for the Red/bad state could have the same cloud with a red line through it to signify not synching with cloud and then when we see the cloud by itself we know it is trying to synch and then when it is complete and good to go we see a checkmark or some other icon that stays there all the time so we know we are good because there is so much anxiety we have from the last few weeks of synch issues and data loss that I really want to be able to glance and see I am currently good to go and all synched and not just trust that no icon is good.

**Comment by Lunariz** [comment]
Agree with text. Why not copy what Google Docs show?

![image](https://user-images.githubusercontent.com/6254272/79923462-746e4580-842d-11ea-96b8-8fbf684e6046.png)
![image](https://user-images.githubusercontent.com/6254272/79923473-7cc68080-842d-11ea-90b3-4c8ecebbb068.png)
![image](https://user-images.githubusercontent.com/6254272/79923486-818b3480-842d-11ea-8ba9-601975536def.png)

**Comment by anshbansal** [comment]
> I didn't add a state/tooltip for when it's done though. Still on the fence if one is needed. Some tools, like Google Keep, have one and I find it nice. But if we can do without, it's one less thing for people to think about.

@filipesilva A Checkmark means Done. The current implementation is making people think the wrong thing. Have you seen checkmark being used to denote Done in any major website?

One suggestion could be different icons for each state or plain text like google does.

**Comment by filipesilva** [comment]
Heya, we've pushed a change that should add the dot always there. Here's how it should look like:

![circle-status](https://user-images.githubusercontent.com/25736/80159041-6e4ca600-85a0-11ea-90a0-db80b2bbb3d0.gif)

If you don't see it yet you can force refresh to update.

**Comment by ryanguill** [comment]
I saw it this morning, its great! Thank you so much @filipesilva!

**Comment by filipesilva** [comment]
@wilkerlucio was the one who did it, thank him :D

**Comment by ryanguill** [comment]
thank you @wilkerlucio!
