### ISSUE TITLE
Zoom Out keyboard shortcut on a block for macOS

### ISSUE THREAD

**Issue by pratul** [Roam-Research/issues#143]
**Describe the bug**

- I cannot zoom out on a block using the keyboard shortcut on macOS -- neither on Firefox, nor Safari. 
- Conor suggested (on Slack) that I try using cmd-shift-comma and that doesn't work either. 
- Zooming in works fine.

**To Reproduce**

1. Use Firefox or Safari on macOS
2. Go to any block
2. Press cmd-dot to zoom in to a new page
3. Press cmd-comma to zoom out back to the old page
4. Will not work; opens browser settings instead

**System Information:**
 - Roam version: 0.6.1-fb84ed08
 - Device: desktop
 - OS: macOS 10.15.4 Catalina
 - Firefox 75.0, Safari 13.1

**Comment by Stvad** [comment]
it overlaps with the standard system shortcut, will work only when cursor within the block =\

**Comment by Matthewspear** [comment]
Interesting observation normally I use Chrome but saw a video tutorial with these shortcuts working in Brave.

I've downloaded and tested in Brave and the zoom in and out shortcuts work – wierd since it also registers `cmd + ,` for preferences and is Chromium based 🤷🏻‍♂️.

**System Information:**
- Roam: 0.6.2-ff9bdc59
- Device: Desktop
- OS: macOS 10.15.4 Catalina
- Brave: Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)

**Comment by Matthewspear** [comment]
The plot thickens slightly further – imported a few of my favourite plugins into Brave, turns out [Cluster – Window & Tab Manager](https://chrome.google.com/webstore/detail/cluster-window-tab-manage/aadahadfdmiibmdhfmpbeeebejmjnkef) was blocking the shortcut from working and once disabled the shortcut works in Chrome!

**Comment by panterarocks49** [comment]
Looked into this a bit today, turns out safari never even fires a keydown event for us on `cmd-comma`, but it does work on `cmd-shift-comma` so we'll probably have to add that shortcut.

**Comment by Matthewspear** [comment]
Yeah `cmd + comma` is reserved for preferences normally, so requires weird remappings

**Comment by gaa23** [comment]
Is this closed resolved or closed... not being worked on?
