### ISSUE TITLE
Changes don't get saved

### ISSUE THREAD

**Issue by jaste111** [Roam-Research/issues#196]
My changes are not synced with the server. I am currently on "947 pending remote changes". My last change on the server is two days ago. I have to export my changes and import them on the next day to work.

**Comment by joshdmiller** [comment]
I've experienced the same problem, but was able to solve it by logging out and logging back in. Because it's in local storage, it did sync the changes when I re-authorized.

In the console, there was a "permission denied" error. It was from Sentry, so it's not clear to me if the error was from Sentry or if Sentry was reporting the error. If it occurs again, I'll attach a screenshot.

**Comment by filipesilva** [comment]
@jaste111 can you try force refreshing your web page?

**Comment by jaste111** [comment]
@filipesilva Meanwhile it is working again. The changes are synced with the server and I can access my notes from a different browser. So I think that my changes are synced and not hold locally in Chrome.

**Comment by filipesilva** [comment]
Might have just been related to the recent server move. Anyway if you start getting this again, let me know.
