### ISSUE TITLE
LaTeX Equations

### ISSUE THREAD

**Issue by robot-love** [Roam-Research/issues#249]
**Describe the problem**

I cannot write and render LaTeX equations in my notes. I'd like to be able to do so without leaving Roam

**Feature implementation**

I would like to be able to write snippets of LaTeX equations, and have them render inline the same way that the image embedding is handled. It's very smooth, allows me to edit the line as text, and shows me the notes the way I expect to see them.

**Additional context**

I'm a grad student, and I'm really enjoying the linking functionality of Roam, and I'd like to be able to work within Roam without switching to another app to handle equations.

**Comment by Itshalffull** [comment]
I think Roam already does this, Try putting the following snippet into roam and you'll see it rendered as an equation.

$$y=mx + b$$

**Comment by tjallemaal** [comment]
i really need this embed function as well.
plus what makes my life miserable is the fact that the RR notation for latex requires double $-signs instead of single ones to wrap text up with. i use roam mainly as a zettelkasten so i can't transfer text from roam to my latex-editor without having to reconfigure all those "dollar-brackets". 
it's a major dealbreaker for my workflow .. 

kinda same thing with markdown ..
https://github.com/Roam-Research/issues/issues/340
