### ISSUE TITLE
When not connected to internet the dot still says Syncing changes remotely

### ISSUE THREAD

**Issue by anshbansal** [Roam-Research/issues#31]
The dot at the top is still the yellowish color when not connected to internet and tooltip says "Saving changes remotely". It would be good to have a red dot that says something like cannot connect.

**Comment by GitMurf** [comment]
I actually posted this same thing a few minutes ago in Slack: https://roamresearch.slack.com/archives/CN5MK4D2M/p1587706764475600?thread_ts=1587706081.474700&cid=CN5MK4D2M

The only thing I would add, in a perfect world, there would be a color/tooltip signifying when you are "offline". Because I just tested disconnecting my internet and it just shows the same Orange "Saving changes remotely..." status and stays like that while you are offline. I see in the Chrome developer console that you recognize when the internet goes out/offline, so maybe you could add a status that is like "Grey" or something that signals Roam sees you as "Offline"?

![image](https://user-images.githubusercontent.com/64155612/80183757-43714a80-85be-11ea-87c9-0f8eab35c9e9.png)

**Comment by filipesilva** [comment]
@wilkerlucio WDYT of adding some extra information to the yellow state when offline?

Something like "Saved changes locally, waiting to go back online to sync with server". Maybe it would help if it was less verbose.

**Comment by GitMurf** [comment]
Yeah that would be too verbose. Would love a different color too. Don’t want to always need to use the tool tip to distinguish. Would love a grey or something for Offline. And I think the tooltip could simply say “Offline” or “Cannot detect Internet” or something like that.

**Comment by pmbauer** [comment]
relying on colors to convey information is not accessibility-friendly; text is best

**Comment by wilkerlucio** [comment]
I have a different suggestion, what you think about changing the orange state message to: "You have local data to sync with the server."

Because I see those more as a "how safe I'm?", so green means all good, orange means we still need to sync server, red means we still need to sync locally.

What do you think?

**Comment by anshbansal** [comment]
> I have a different suggestion, what you think about changing the orange state message to: "You have local data to sync with the server."

Agree with the sentiment. The wording is verbose. "Synced to server", "Needs sync to server" and "Needs sync to local" might be better.

**Comment by GitMurf** [comment]
Honestly right now is pretty much perfect to me other than I’d like an additional indicator when you are considered offline. So I can quickly see if Roam believes I’m offline and I can check my internet connection etc. Really I’m wanting to know what Roam is “thinking” my current state is because if I’m clearly connected to the internet but Roam says it thinks I’m offline then I know there’s a problem. Also if there is a different color/message for being offline (I’m thinking like a Grey or something) I can get a better idea of whether there is some server/sync issue or if simply Roam just considers me in offline mode due to internet connectivity. 

My opinion is if you don’t add another color / tooltip message for being offline then my vote is just keep things the way they are and don’t mess with it too much.

**Comment by aemt** [comment]
Please add a non-hover secondary indicator (such as an outline or fill dot) to indicate current status. The current colors may not be distinguishable for someone with colorblindness, and asking those users to constantly leave their keyboard to hover their mouse for the tool tip is not great UX.

**Comment by panterarocks49** [comment]
Changed the tooltip to let you know when you are online/offline and some other info

![image](https://user-images.githubusercontent.com/4172079/81199440-8ec22a80-8fba-11ea-890f-be1d8f00d375.png)

![image](https://user-images.githubusercontent.com/4172079/81199455-941f7500-8fba-11ea-9218-739f0c198d1f.png)
