### ISSUE TITLE
Accented characters mess with the cursor somehow

### ISSUE THREAD

**Issue by MarcCoet** [Roam-Research/issues#53]
**Describe the bug**

The problems I found with accented chars (AC for short here):
- typing an AC then any other character: the cursor jumps before the the last character when we stop typing
- hitting `backspace` on an AC: the char gets replaced by its non accented version = the accent gets removed but not the char

This happens when we stop typing for a second then do these actions. It does not happen when typing the character then directly hitting `backspace` for example.
If we type a word with an accented character in it, it is only when we stop writing for a second that the cursor jump happens.

Behavior 2 seems not to happen on Safari

**To Reproduce**

Typing accented chars in a page should do

**System Information:**
Tested on:
- Chromebook + Chrome browser
- Android + Brave browser
- Mac + Chrome
- Mac + Safari

**Additional context**

**Comment by MarcCoet** [comment]
Might or might not be related with #46 since it is cursor behavior.

**Comment by panpiotrs** [comment]
That, plus, Roam **sometimes** creates new pages instead of linking to existing, when there are AC in the title. Something changed in how the characters are recognized. Example here https://github.com/Roam-Research/issues/issues/44#issuecomment-621249960
One need then to change the title of original page, otherwise there is no way to link to that page.

**Comment by panpiotrs** [comment]
Due to these bugs Roam is unusable. I thought it affected some pages, but no, every page with AC created before this recent change is affected. I would need now to go through all my pages to remove AC from titles and type them again. Please revert this recent (yesterday's?) change.

**Comment by dalmo3** [comment]
Can confirm both of OP's issues exactly as described.

I've been having issues with cursor going awry while typing but hadn't noticed any patterns. It could well be a deeper parsing issue than with just ACs.

**Comment by kalmir** [comment]
I'm experiencing this too.

Back-jumping cursor makes writing anything longer in Roam impossible.

I'm not sure if "creating new pages instead of linking to existing" happened to me. Most of my titles are without AC. I quickly checked some AC-carrying pages and they seem ok. But will need to investigate more.

**Comment by MrPiotrS** [comment]
@kalmir back-jumping cursor means your accented letters are updated to another version.

> I'm not sure if "creating new pages instead of linking to existing" happened to me.
You can check if you have a problem. Open "All pages", scroll down to some older notes, if you see one with AC try to find it in "Find or Create Page". If it disappear from there as soon as you type AC, it means you have the same problem. You also then can't search for normal content with AC in older notes. Which means now you have two versions of notes in your DB and it affects backups too, but in opposite way, on your desktop with some markdown app you will not be able to search for newer notes because your OS doesn't use this version of AC.
I recreated that also in Roam on Android. There are no backjumping cursor, but I can't search for my older notes (titles and content) and everything I write there is updated to this new version.

**Comment by slaapme** [comment]
Same bug here !

**Comment by magnus-w** [comment]
Hmm...am I rusty at ASCII or is this a bit of a stretched definition of 'accented'? I would call it 'international characters', since I didn't have any accented ones but a Swedish one. (å, ä, ö). Desktop browser and iPad Safari are both running UTF-8, though.

**Comment by magnus-w** [comment]
OK, tracked it carefully now: Writing in Swedish, I do something ending with an 'ä' and then spacebar. I wait for a second and the cursor backjumps. Wait another and the 'ä' is automagically transformed to an 'a'. Roam doesn't want me to write in my native tongue! :-)

**Comment by kalmir** [comment]
My case is with Czech diacritics – á, š, ě, ť - and such.

**Comment by slaapme** [comment]
This is an important BUG because it create pages different from the original and break links... snif.

<img width="204" alt="Screenshot 2020-05-01 at 23 13 15" src="https://user-images.githubusercontent.com/7404748/80842494-07636880-8c02-11ea-9861-be1380258886.png">

**Comment by MarcCoet** [comment]
Thanks @panterarocks49
