### ISSUE TITLE
Accented keyboard layouts are not working on desktop Roam

### ISSUE THREAD

**Issue by thesved** [Roam-Research/issues#605]
**Describe the bug**
Roam can't write accented characters in languages where you 
- **first write an accent** 
- then a **letter**

See: https://cln.sh/p8wJhC8a1yQJqExGlJ0x

It **works** in 
- TextEdit: https://cln.sh/kVgDP3TrQC5LqkCvlImn
- iPad

**To Reproduce**

1. Change keyboard layout for example to Czech in OS
2. Write accent, like `ˇ`
3. Write a letter, like `s`
4. The accent gets replaced by the letter, instead of `š` it becomes simply `s`

**System Information:**
 - Roam version: 0.7.5-41613cc4
 - Device: desktop
 - OS: mac
 - Browser: chrome

**Comment by gustavobio** [comment]
I see this when using Safari on my Macbook, but not on Chrome. Same behavior when typing Portuguese characters. You first type the accent, for some reason the accent is select, and the next character, the letter, replaces the selected accent. There are a few issues here reporting this behavior for different languages and nothing has been done.

**Comment by tombarys** [comment]
It is frustrating enough. French has the problem, too: https://forum.roamresearch.com/t/french-accents-in-roam-safari/2416/2. 

I played several hours with BetterTouchTool, macOS text replacements, and TextExpander. Nothing worked. 

Please, please, solve this basic bug, @Bardia95. Thanks! Roam Believer.

**Comment by gustavobio** [comment]
Crazy how long it's taking to solve this.

**Comment by tombarys** [comment]
Yes, I hate this too. 

Gustavo, I found a simple temporary solution: press accent twice before pressing the letter. It works for me. For you?

**Comment by gustavobio** [comment]
@tombarys It does work, thanks! I only have this problem on Safari, so I've been using Chrome meanwhile. Really wish they'd just fix this though.

**Comment by tombarys** [comment]
Yes...

Another problem that bothers me (in Safari only) after recent update is

this: https://github.com/Roam-Research/issues/issues/634. Same with you

or problem just on my side? 

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Roam-Research/issues/issues/605#issuecomment-
738125060>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABLWYSBYNRIWXVIDZ5OLF6DSS65ELANCNFSM4TSPPGDQ>.

**Comment by gustavobio** [comment]
Any news on this? This issue is very disrupting for people using accented languages. A quick look at the list of issues here shows several others that are likely related to this one.

**Comment by tombarys** [comment]
Oh, no! I mentioned that @thesved posted the issue with wrong mention of Chrome. This issue is Safari only! I hope that is the reason @Bardia95 and Roam product team has not reproduced the issue so they do not care. Please, can you look at this? 

How it should work with accents: https://cln.sh/kVgDP3TrQC5LqkCvlImn (with others too: ˇ ' ¨ etc.)
This is wrong behavior: https://cln.sh/p8wJhC8a1yQJqExGlJ0x

Thank you, @Bardia95 !

**Comment by Bardia95** [comment]
@theSherwood fixed this for y'all!

**Comment by tombarys** [comment]
Oh, this is great! Fantastic! I can write again! :) thanks.
